export interface EServicesModel {
    firstName: string,
    lastName: string,
    userId: string,
    userStatus: string,
    userCell: number,
    userEmail: string,
    isUserMigrated: string,
    createdBy: string,
    createdWhen: string,
    modifiedBy: string,
    modifiedWhen: string,
    userGender: string,
    userCro: string,
    businessCategory: string,
    employeeType: string,
    adUser: string,
    userPassword: string,
    employeeId: number,
    userDesignation: string,
    userDepartment: string,
    userLocation: string
}